//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuliusSweetland.OptiKids.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JuliusSweetland.OptiKids.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Dark.
        /// </summary>
        public static string ANDROID_DARK {
            get {
                return ResourceManager.GetString("ANDROID_DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android Light.
        /// </summary>
        public static string ANDROID_LIGHT {
            get {
                return ResourceManager.GetString("ANDROID_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bass was unable to create a stream from file &apos;{0}&apos;.
        /// </summary>
        public static string BASS_UNABLE_TO_CREATE_STREAM_FROM_FILE {
            get {
                return ResourceManager.GetString("BASS_UNABLE_TO_CREATE_STREAM_FROM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the quiz. Please check the quiz file and try again....
        /// </summary>
        public static string CANNOT_START_QUIZ_CONTENT {
            get {
                return ResourceManager.GetString("CANNOT_START_QUIZ_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UH-OH!.
        /// </summary>
        public static string CANNOT_START_QUIZ_TITLE {
            get {
                return ResourceManager.GetString("CANNOT_START_QUIZ_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates on startup:.
        /// </summary>
        public static string CHECK_FOR_UPDATES_AT_STARTUP_LABEL {
            get {
                return ResourceManager.GetString("CHECK_FOR_UPDATES_AT_STARTUP_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct!|That’s right!|You did it!|Well done!|That is correct!|Nicely done!|Nice!|Good spelling!|Yes!|Amazing!|You’re very good at spelling!|That’s great!|Excellent!|Brilliant!|Absolutely right!|Exactly right!|Nice!|Perfect!|You got it!.
        /// </summary>
        public static string CORRECT_SPELLING_ENCOURAGEMENTS {
            get {
                return ResourceManager.GetString("CORRECT_SPELLING_ENCOURAGEMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiKids has detected that your user settings file has become corrupted and must be repaired. This will be done by restoring an old version, or a default version if that isn&apos;t possible.
        ///
        ///Click Yes to reset your user settings and restart.
        ///
        ///Click No to close so that you can manually repair or copy your user settings file..
        /// </summary>
        public static string CORRUPTED_SETTINGS_MESSAGE {
            get {
                return ResourceManager.GetString("CORRUPTED_SETTINGS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-oh! The user settings file looks to be corrupt..
        /// </summary>
        public static string CORRUPTED_SETTINGS_TITLE {
            get {
                return ResourceManager.GetString("CORRUPTED_SETTINGS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad news - OptiKids has tripped over its feet and has to close down.
        ///
        ///An email with details of what happened would be very helpful: optikeyfeedback@gmail.com
        ///
        ///Sorry for the inconvenience..
        /// </summary>
        public static string CRASH_MESSAGE {
            get {
                return ResourceManager.GetString("CRASH_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uh-oh!.
        /// </summary>
        public static string CRASH_TITLE {
            get {
                return ResourceManager.GetString("CRASH_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging mode:.
        /// </summary>
        public static string DEBUGGING_MODE_LABEL {
            get {
                return ResourceManager.GetString("DEBUGGING_MODE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay before progressing questions (seconds):.
        /// </summary>
        public static string DELAY_BEFORE_PROGRESSING_IN_SECONDS {
            get {
                return ResourceManager.GetString("DELAY_BEFORE_PROGRESSING_IN_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display for X seconds per message character:.
        /// </summary>
        public static string DISPLAY_FOR_X_SECONDS_PER_CHARACTER_LABEL {
            get {
                return ResourceManager.GetString("DISPLAY_FOR_X_SECONDS_PER_CHARACTER_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ({0:#,###}ms).
        /// </summary>
        public static string DURATION_FORMAT {
            get {
                return ResourceManager.GetString("DURATION_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error:.
        /// </summary>
        public static string ERROR_SOUND_LABEL {
            get {
                return ResourceManager.GetString("ERROR_SOUND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Pie.
        /// </summary>
        public static string FILL_PIE {
            get {
                return ResourceManager.GetString("FILL_PIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixations (dwell).
        /// </summary>
        public static string FIXATIONS_DWELL {
            get {
                return ResourceManager.GetString("FIXATIONS_DWELL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FONT {
            get {
                return ResourceManager.GetString("FONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font family:.
        /// </summary>
        public static string FONT_FAMILY_LABEL {
            get {
                return ResourceManager.GetString("FONT_FAMILY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font stretch:.
        /// </summary>
        public static string FONT_STRETCH_LABEL {
            get {
                return ResourceManager.GetString("FONT_STRETCH_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font weight:.
        /// </summary>
        public static string FONT_WEIGHT_LABEL {
            get {
                return ResourceManager.GetString("FONT_WEIGHT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gaze Tracker.
        /// </summary>
        public static string GAZE_TRACKER {
            get {
                return ResourceManager.GetString("GAZE_TRACKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grow.
        /// </summary>
        public static string GROW {
            get {
                return ResourceManager.GetString("GROW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string HIGH {
            get {
                return ResourceManager.GetString("HIGH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontal fill (as % of screen):.
        /// </summary>
        public static string HORIZONTAL_FILL {
            get {
                return ResourceManager.GetString("HORIZONTAL_FILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete key fixation time to live (ms):.
        /// </summary>
        public static string INCOMPLETE_KEY_FIXATION_TTL_LABEL {
            get {
                return ResourceManager.GetString("INCOMPLETE_KEY_FIXATION_TTL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info:.
        /// </summary>
        public static string INFO_SOUND_LABEL {
            get {
                return ResourceManager.GetString("INFO_SOUND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiKids.
        /// </summary>
        public static string INTRO_SCREEN_TITLE {
            get {
                return ResourceManager.GetString("INTRO_SCREEN_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key fixation time to complete (ms):.
        /// </summary>
        public static string KEY_FIXATION_TIME_TO_COMPLETE_LABEL {
            get {
                return ResourceManager.GetString("KEY_FIXATION_TIME_TO_COMPLETE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key fixation time to lock-on (ms):.
        /// </summary>
        public static string KEY_FIXATION_TIME_TO_LOCK_ON_LABEL {
            get {
                return ResourceManager.GetString("KEY_FIXATION_TIME_TO_LOCK_ON_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key selection keyboard key:.
        /// </summary>
        public static string KEY_SELECTION_KEYBOARD_KEY_LABEL {
            get {
                return ResourceManager.GetString("KEY_SELECTION_KEYBOARD_KEY_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key selection mouse button:.
        /// </summary>
        public static string KEY_SELECTION_MOUSE_BUTTON_LABEL {
            get {
                return ResourceManager.GetString("KEY_SELECTION_MOUSE_BUTTON_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Selection:.
        /// </summary>
        public static string KEY_SELECTION_SOUND_LABEL {
            get {
                return ResourceManager.GetString("KEY_SELECTION_SOUND_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key selection source:.
        /// </summary>
        public static string KEY_SELECTION_SOURCE_LABEL {
            get {
                return ResourceManager.GetString("KEY_SELECTION_SOURCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key selection: {0}.
        /// </summary>
        public static string KEY_SELECTION_TRIGGER_DESCRIPTION {
            get {
                return ResourceManager.GetString("KEY_SELECTION_TRIGGER_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyboard key.
        /// </summary>
        public static string KEYBOARD_KEY {
            get {
                return ResourceManager.GetString("KEYBOARD_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Look.
        /// </summary>
        public static string LOOK {
            get {
                return ResourceManager.GetString("LOOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string LOW {
            get {
                return ResourceManager.GetString("LOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management Console.
        /// </summary>
        public static string MANAGEMENT_CONSOLE {
            get {
                return ResourceManager.GetString("MANAGEMENT_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Settings  .
        /// </summary>
        public static string MANAGEMENT_CONSOLE_BUTTON {
            get {
                return ResourceManager.GetString("MANAGEMENT_CONSOLE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management console: ALT + M.
        /// </summary>
        public static string MANAGEMENT_CONSOLE_DESCRIPTION {
            get {
                return ResourceManager.GetString("MANAGEMENT_CONSOLE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiKids Management Console.
        /// </summary>
        public static string MANAGEMENT_CONSOLE_TITLE {
            get {
                return ResourceManager.GetString("MANAGEMENT_CONSOLE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string MEDIUM {
            get {
                return ResourceManager.GetString("MEDIUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min image display time (seconds):.
        /// </summary>
        public static string MIN_IMAGE_DISPLAY_TIME_IN_SECONDS {
            get {
                return ResourceManager.GetString("MIN_IMAGE_DISPLAY_TIME_IN_SECONDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc.
        /// </summary>
        public static string MISC {
            get {
                return ResourceManager.GetString("MISC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse button.
        /// </summary>
        public static string MOUSE_BUTTON {
            get {
                return ResourceManager.GetString("MOUSE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse position.
        /// </summary>
        public static string MOUSE_POSITION {
            get {
                return ResourceManager.GetString("MOUSE_POSITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse position sample interval (ms):.
        /// </summary>
        public static string MOUSE_POSITION_SAMPLE_INTERVAL_LABEL {
            get {
                return ResourceManager.GetString("MOUSE_POSITION_SAMPLE_INTERVAL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to myGaze! Please check that the server is running and the device is connected and try again..
        /// </summary>
        public static string MY_GAZE_CONNECT_ERROR {
            get {
                return ResourceManager.GetString("MY_GAZE_CONNECT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NO_SOUND {
            get {
                return ResourceManager.GetString("NO_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string NONE {
            get {
                return ResourceManager.GetString("NONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string NOTIFICATIONS {
            get {
                return ResourceManager.GetString("NOTIFICATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string OTHER {
            get {
                return ResourceManager.GetString("OTHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Window could not be identified. Unable to continue.
        /// </summary>
        public static string PARENT_WINDOW_COULD_NOT_BE_FOUND {
            get {
                return ResourceManager.GetString("PARENT_WINDOW_COULD_NOT_BE_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play encouragement on correctly spelled word:.
        /// </summary>
        public static string PLAY_ENCOURAGEMENT_ON_CORRECTLY_SPELLED_WORD {
            get {
                return ResourceManager.GetString("PLAY_ENCOURAGEMENT_ON_CORRECTLY_SPELLED_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string PLAY_SOUND {
            get {
                return ResourceManager.GetString("PLAY_SOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointing &amp; Selecting.
        /// </summary>
        public static string POINT_AND_SELECTING {
            get {
                return ResourceManager.GetString("POINT_AND_SELECTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pointing.
        /// </summary>
        public static string POINTING {
            get {
                return ResourceManager.GetString("POINTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROBLEM LOADING KEYBOARD.
        /// </summary>
        public static string PROBLEM_LOADING_KEYBOARD {
            get {
                return ResourceManager.GetString("PROBLEM_LOADING_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pronunciation file:.
        /// </summary>
        public static string PRONUNCIATION_FILE {
            get {
                return ResourceManager.GetString("PRONUNCIATION_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     Quit    .
        /// </summary>
        public static string QUIT {
            get {
                return ResourceManager.GetString("QUIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you would like to quit?.
        /// </summary>
        public static string QUIT_MESSAGE {
            get {
                return ResourceManager.GetString("QUIT_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string QUIT_TITLE_CASE {
            get {
                return ResourceManager.GetString("QUIT_TITLE_CASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You completed the quiz. Congratulations!.
        /// </summary>
        public static string QUIZ_COMPLETE_CONTENT {
            get {
                return ResourceManager.GetString("QUIZ_COMPLETE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WOO-HOO!.
        /// </summary>
        public static string QUIZ_COMPLETE_TITLE {
            get {
                return ResourceManager.GetString("QUIZ_COMPLETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Which quiz should we run?.
        /// </summary>
        public static string QUIZ_FILE {
            get {
                return ResourceManager.GetString("QUIZ_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General speech rate:.
        /// </summary>
        public static string RATE_LABEL {
            get {
                return ResourceManager.GetString("RATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio service was not supplied to the management window action..
        /// </summary>
        public static string REQUIRED_SERVICES_NOT_PASSED_TO_MANAGEMENT_WINDOW {
            get {
                return ResourceManager.GetString("REQUIRED_SERVICES_NOT_PASSED_TO_MANAGEMENT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OptiKids needs to restart to apply your changes.
        ///Please click OK to continue with the restart, or CANCEL to discard your changes.
        /// </summary>
        public static string RESTART_MESSAGE {
            get {
                return ResourceManager.GetString("RESTART_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuming an incomplete key fixation requires a new lock on:.
        /// </summary>
        public static string RESUMING_INCOMPLETE_KEY_FIXATION_REQUIRES_NEW_LOCK_ON_LABEL {
            get {
                return ResourceManager.GetString("RESUMING_INCOMPLETE_KEY_FIXATION_REQUIRES_NEW_LOCK_ON_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection.
        /// </summary>
        public static string SELECTION {
            get {
                return ResourceManager.GetString("SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection progress indicator behaviour:.
        /// </summary>
        public static string SELECTION_PROGRESS_INDICATOR_BEHAVIOUR_LABEL {
            get {
                return ResourceManager.GetString("SELECTION_PROGRESS_INDICATOR_BEHAVIOUR_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection progress indicator end size (%):.
        /// </summary>
        public static string SELECTION_PROGRESS_INDICATOR_END_SIZE_LABEL {
            get {
                return ResourceManager.GetString("SELECTION_PROGRESS_INDICATOR_END_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection progress indicator start size (%):.
        /// </summary>
        public static string SELECTION_PROGRESS_INDICATOR_START_SIZE_LABEL {
            get {
                return ResourceManager.GetString("SELECTION_PROGRESS_INDICATOR_START_SIZE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink.
        /// </summary>
        public static string SHRINK_INDICATOR {
            get {
                return ResourceManager.GetString("SHRINK_INDICATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects.
        /// </summary>
        public static string SOUND_EFFECTS {
            get {
                return ResourceManager.GetString("SOUND_EFFECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        public static string SOUNDS {
            get {
                return ResourceManager.GetString("SOUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string SOURCE_LABEL {
            get {
                return ResourceManager.GetString("SOURCE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech.
        /// </summary>
        public static string SPEECH {
            get {
                return ResourceManager.GetString("SPEECH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spelling speech rate:.
        /// </summary>
        public static string SPELLING_RATE_LABEL {
            get {
                return ResourceManager.GetString("SPELLING_RATE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string START_QUIZ_BUTTON {
            get {
                return ResourceManager.GetString("START_QUIZ_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good luck. You&apos;ll be great!.
        /// </summary>
        public static string START_QUIZ_CONTENT {
            get {
                return ResourceManager.GetString("START_QUIZ_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here we go....
        /// </summary>
        public static string START_QUIZ_TITLE {
            get {
                return ResourceManager.GetString("START_QUIZ_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Eye Tribe.
        /// </summary>
        public static string THE_EYE_TRIBE {
            get {
                return ResourceManager.GetString("THE_EYE_TRIBE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to activate TheEyeTribe GazeManager! Please check that the server is running and the device is connected and try again..
        /// </summary>
        public static string THE_EYE_TRIBE_ACTIVATION_ERROR {
            get {
                return ResourceManager.GetString("THE_EYE_TRIBE_ACTIVATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TheEyeTribe has not been calibrated. No data will be received until calibration is completed..
        /// </summary>
        public static string THE_EYE_TRIBE_NOT_CALIBRATED {
            get {
                return ResourceManager.GetString("THE_EYE_TRIBE_NOT_CALIBRATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attempt a calibration as no EyeX engine is available..
        /// </summary>
        public static string THE_EYE_TRIBE_UNABLE_TO_CALIBRATE_NO_ENGINE {
            get {
                return ResourceManager.GetString("THE_EYE_TRIBE_UNABLE_TO_CALIBRATE_NO_ENGINE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme:.
        /// </summary>
        public static string THEME_LABEL {
            get {
                return ResourceManager.GetString("THEME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time until point becomes irrelevent (ms):.
        /// </summary>
        public static string TIME_UNTIL_POINT_BECOMES_IRRELEVENT_LABEL {
            get {
                return ResourceManager.GetString("TIME_UNTIL_POINT_BECOMES_IRRELEVENT_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobii EyeX.
        /// </summary>
        public static string TOBII_EYEX {
            get {
                return ResourceManager.GetString("TOBII_EYEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calibration completed, or possibly cancelled, but everything is working again!.
        /// </summary>
        public static string TOBII_EYEX_CALIBRATION_SUCCESS {
            get {
                return ResourceManager.GetString("TOBII_EYEX_CALIBRATION_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data stream processing amount:.
        /// </summary>
        public static string TOBII_EYEX_DATA_STREAM_PROCESSING_LEVEL {
            get {
                return ResourceManager.GetString("TOBII_EYEX_DATA_STREAM_PROCESSING_LEVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobii EyeX Engine cannot be found. Please install the EyeX Engine and try again..
        /// </summary>
        public static string TOBII_EYEX_ENGINE_NOT_FOUND {
            get {
                return ResourceManager.GetString("TOBII_EYEX_ENGINE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobii EyeX Engine is not running. Please start the EyeX Engine and try again..
        /// </summary>
        public static string TOBII_EYEX_ENGINE_NOT_RUNNING {
            get {
                return ResourceManager.GetString("TOBII_EYEX_ENGINE_NOT_RUNNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobii PCEye Go.
        /// </summary>
        public static string TOBII_PCEYE_GO {
            get {
                return ResourceManager.GetString("TOBII_PCEYE_GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tobii REX.
        /// </summary>
        public static string TOBII_REX {
            get {
                return ResourceManager.GetString("TOBII_REX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone 1.
        /// </summary>
        public static string TONE_SOUND_1 {
            get {
                return ResourceManager.GetString("TONE_SOUND_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone 2.
        /// </summary>
        public static string TONE_SOUND_2 {
            get {
                return ResourceManager.GetString("TONE_SOUND_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone 3.
        /// </summary>
        public static string TONE_SOUND_3 {
            get {
                return ResourceManager.GetString("TONE_SOUND_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tone 4.
        /// </summary>
        public static string TONE_SOUND_4 {
            get {
                return ResourceManager.GetString("TONE_SOUND_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can not detect where you are directing your attention. Is there a problem with the input device? Is it connected, turned on, calibrated, etc?.
        /// </summary>
        public static string TRIGGER_WITHOUT_POSITION_ERROR {
            get {
                return ResourceManager.GetString("TRIGGER_WITHOUT_POSITION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the current elevation..
        /// </summary>
        public static string UNABLE_TO_DETERMINE_CURRENT_ELEVATION {
            get {
                return ResourceManager.GetString("UNABLE_TO_DETERMINE_CURRENT_ELEVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to render keyboard! Check the logs..
        /// </summary>
        public static string UNABLE_TO_RENDER_KEYBOARD {
            get {
                return ResourceManager.GetString("UNABLE_TO_RENDER_KEYBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem setting the voice to &apos;{0}&apos;{1}.
        /// </summary>
        public static string UNABLE_TO_SET_VOICE_WARNING {
            get {
                return ResourceManager.GetString("UNABLE_TO_SET_VOICE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, but I don&apos;t know what - please check the logs.
        /// </summary>
        public static string UNKNOWN_CALIBRATION_ERROR {
            get {
                return ResourceManager.GetString("UNKNOWN_CALIBRATION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE AVAILABLE!.
        /// </summary>
        public static string UPDATE_AVAILABLE {
            get {
                return ResourceManager.GetString("UPDATE_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please visit https://github.com/OptiKey/OptiKids to download latest version ({0})
        ///You can turn off update checks from the Management Console (ALT + M)..
        /// </summary>
        public static string URL_DOWNLOAD_PROMPT {
            get {
                return ResourceManager.GetString("URL_DOWNLOAD_PROMPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May I restart OptiKids?.
        /// </summary>
        public static string VERIFY_RESTART {
            get {
                return ResourceManager.GetString("VERIFY_RESTART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertical fill (as % of screen):.
        /// </summary>
        public static string VERTICAL_FILL_LABEL {
            get {
                return ResourceManager.GetString("VERTICAL_FILL_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Interaction myGaze.
        /// </summary>
        public static string VI_MYGAZE {
            get {
                return ResourceManager.GetString("VI_MYGAZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visuals.
        /// </summary>
        public static string VISUALS {
            get {
                return ResourceManager.GetString("VISUALS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (from settings).
        /// </summary>
        public static string VOICE_COMES_FROM_SETTINGS {
            get {
                return ResourceManager.GetString("VOICE_COMES_FROM_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice:.
        /// </summary>
        public static string VOICE_LABEL {
            get {
                return ResourceManager.GetString("VOICE_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General speech volume:.
        /// </summary>
        public static string VOLUME_LABEL {
            get {
                return ResourceManager.GetString("VOLUME_LABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word to spell speech rate:.
        /// </summary>
        public static string WORD_RATE_LABEL {
            get {
                return ResourceManager.GetString("WORD_RATE_LABEL", resourceCulture);
            }
        }
    }
}
